### PR TITLE
Move redis to longlife nodes

### PR DESCRIPTION
**Pull request by adammcmaster**

### CODE REVIEW

**Comment by camallen** [comment]
I don't think we need to remove the redis pod for cellect deployment, as it's not critical and any odd latency issues will have minimal impact on the cellect service.

Cellect uses redis for node discovery for clients. We've removed the use of this service discovery in panoptes client via https://github.com/zooniverse/panoptes/pull/3259. instead we use the ingress DNS request path

**Comment by adammcmaster** [comment]
Oh, so this is basically not using redis any more?

**Comment by camallen** [comment]
It's still required for cellect as the server registers the node IPs in redis but we don't use those IPs in the client for service discovery. 

So the client feature isn't used but server still uses redis - i don't want to do any engineering work on cellect to fix this.

**Comment by adammcmaster** [comment]
👍 In that case I'll close this.

**Pull request closed without merging**
